version: '3.5'

services:
  postgres:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      DATABASE_HOST: 172.0.0.1
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: camp_manager_db
    volumes:
      #- ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
    - "5050:80"

  backend:
    container_name: spring_boot
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    #      - ./.m2:/root/.m2
    working_dir: /app
    #    command: sh run.sh
    depends_on:
      - "postgres"
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005