version: '3.5'

services:
  postgres:
    container_name: pg_container
    image: postgres:15
    restart: always
    environment:
      DATABASE_HOST: 172.0.0.1
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: camp_manager_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "--host=pg_container", "--port=5432", "--username=admin" ]
      interval: 15s
      timeout: 30s
      retries: 40
      start_period: 30s

  pgadmin:
    container_name: pgadmin_4
    image: dpage/pgadmin4
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
    - "5050:80"

  backend:
    container_name: spring_boot
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
      - 28000:28000
    depends_on:
      postgres:
        condition: "service_healthy"

volumes:
  postgres-data: