version: '3.5'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
#      - ./.m2:/root/.m2
    working_dir: /app
#    command: sh run.sh
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005